"""Invoke REFACTOR_TJSP-main to generate final JSON for discovered precatórios."""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from tjsp_pipeline.config import Settings
from tjsp_pipeline.scraper.show_page import PrecatorioRecord

logger = logging.getLogger(__name__)


# Keys always synced from dashboard Settings into REFACTOR .env (API runtime).
_FORCE_SYNC_KEYS = frozenset(
    {
        "ENABLE_PERSISTENCE",
        "CALCULO_API_URL",
        "CALCULO_API_TOKEN",
        "USE_CALCULO_API",
        "GEMINI_API_KEY",
        "USE_GEMINI_API",
    }
)


def ensure_refactor_env(settings: Settings) -> Path:
    """Ensure REFACTOR .env has DB + SQL required for --txt preenchimento/reprocessamento."""
    env_path = settings.refactor_path / ".env"
    required = {
        "FLASK_DB_HOST": settings.flask_db_host,
        "FLASK_DB_PORT": settings.flask_db_port,
        "FLASK_DB_USER": settings.flask_db_user,
        "FLASK_DB_PASSWORD": settings.flask_db_password,
        "FLASK_DB_DATABASE": settings.flask_db_database,
        "PREENCHIMENTO_SQL": settings.preenchimento_sql,
        # Required by Config.validate(--reprocessamento); --txt replaces the SQL queue.
        "REPROCESSAMENTO_SQL": (
            settings.preenchimento_sql
            if "controle_coleta" in settings.preenchimento_sql.lower()
            or "precainfosnew" in settings.preenchimento_sql.lower()
            else (
                "SELECT id, numero_de_processo, numero_do_incidente "
                "FROM controle_coleta_TJSP LIMIT 1"
            )
        ),
        "ENABLE_PERSISTENCE": settings.enable_persistence,
        "HTTP_VERIFY_SSL": "false",
        "LOG_LEVEL": "INFO",
        "CALCULO_API_URL": settings.calculo_api_url,
        "CALCULO_API_TOKEN": settings.calculo_api_token,
        "USE_CALCULO_API": (
            "true"
            if settings.calculo_api_configured
            and str(settings.use_calculo_api).strip().lower()
            in {"1", "true", "yes", "on", ""}
            else (settings.use_calculo_api or "false")
        ),
    }
    if settings.gemini_api_key:
        required["GEMINI_API_KEY"] = settings.gemini_api_key
    if settings.use_gemini_api:
        required["USE_GEMINI_API"] = settings.use_gemini_api

    existing: dict[str, str] = {}
    if env_path.is_file():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if not line.strip() or line.strip().startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            existing[key.strip()] = value

    changed = False
    for key, value in required.items():
        missing_or_blank = key not in existing or not str(existing.get(key, "")).strip()
        force = key in _FORCE_SYNC_KEYS and str(value).strip() != ""
        # Always push ENABLE_PERSISTENCE / USE_CALCULO_API even when "false".
        force_boolish = key in {"ENABLE_PERSISTENCE", "USE_CALCULO_API"}
        if missing_or_blank or force or force_boolish:
            if existing.get(key) != value:
                existing[key] = value
                changed = True

    if changed or not env_path.is_file():
        lines = [f"{k}={v}" for k, v in existing.items()]
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Updated REFACTOR .env at %s", env_path)
    return env_path


def write_processos_txt(
    records: list[PrecatorioRecord],
    target_path: Path,
) -> Path:
    lines = ["# Generated by dashboard-backend tjsp_pipeline"]
    for record in records:
        lines.append(record.txt_line)
    target_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s processo(s) to %s", len(records), target_path)
    return target_path


def run_refactor(
    settings: Settings,
    txt_filename: str,
    *,
    mode: str | None = None,
) -> subprocess.CompletedProcess[str]:
    ensure_refactor_env(settings)
    main_py = settings.refactor_path / "main.py"
    if not main_py.is_file():
        raise FileNotFoundError(f"REFACTOR main.py not found: {main_py}")

    # Linux: .venv/bin/python  |  Windows: .venv/Scripts/python.exe (or venv/)
    candidates = (
        settings.refactor_path / ".venv" / "Scripts" / "python.exe",
        settings.refactor_path / "venv" / "Scripts" / "python.exe",
        settings.refactor_path / ".venv" / "bin" / "python",
        settings.refactor_path / "venv" / "bin" / "python",
    )
    python_bin = str(sys.executable)
    for candidate in candidates:
        if candidate.is_file():
            python_bin = str(candidate)
            break

    resolved_mode = (mode or settings.refactor_mode).strip().lower()
    cmd = [python_bin, str(main_py)]
    if resolved_mode == "reprocessamento":
        cmd.append("--reprocessamento")
    else:
        cmd.append("--preenchimento")
    if settings.refactor_test_mode:
        cmd.append("--test")
    cmd.extend(["--txt", txt_filename])

    logger.info("Running REFACTOR: %s", " ".join(cmd))
    env = os.environ.copy()
    env["HTTP_PROXY"] = settings.proxy.requests_url
    env["HTTPS_PROXY"] = settings.proxy.requests_url
    return subprocess.run(
        cmd,
        cwd=str(settings.refactor_path),
        capture_output=True,
        text=True,
        timeout=3600,
        check=False,
        env=env,
    )


# Back-compat alias
def run_refactor_preenchimento(
    settings: Settings,
    txt_filename: str,
) -> subprocess.CompletedProcess[str]:
    return run_refactor(settings, txt_filename)


def json_paths_for_records(
    settings: Settings,
    records: list[PrecatorioRecord],
) -> list[Path]:
    import re

    def _slug(value: str) -> str:
        return re.sub(r"[^\w.-]+", "_", value).strip("_")[:60] or "record"

    source_dir = settings.refactor_path / "output" / "json"
    if not source_dir.is_dir():
        return []
    found: list[Path] = []
    for record in records:
        prefix = f"{_slug(record.numero_de_processo)}_{_slug(record.numero_do_incidente)}"
        for path in sorted(source_dir.glob(f"{prefix}*.json")):
            found.append(path)
    return found


def collect_refactor_json_outputs(
    settings: Settings,
    dest_dir: Path,
    *,
    run_id: str | None = None,
    records: list[PrecatorioRecord] | None = None,
) -> list[Path]:
    """Copy JSON artifacts from REFACTOR output/json into dashboard-backend logs."""
    source_dir = settings.refactor_path / "output" / "json"
    if not source_dir.is_dir():
        logger.warning("REFACTOR json output dir missing: %s", source_dir)
        return []

    dest_dir.mkdir(parents=True, exist_ok=True)
    stamp = run_id or datetime.now().strftime("%Y%m%d_%H%M%S")
    copied: list[Path] = []

    prefixes: list[str] = []
    if records:
        import re

        def _slug(value: str) -> str:
            return re.sub(r"[^\w.-]+", "_", value).strip("_")[:60] or "record"

        for record in records:
            prefixes.append(
                f"{_slug(record.numero_de_processo)}_{_slug(record.numero_do_incidente)}"
            )

    sources = sorted(source_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    for src in sources:
        if prefixes and not any(src.name.startswith(prefix) for prefix in prefixes):
            continue
        dest = dest_dir / f"{stamp}_{src.name}"
        shutil.copy2(src, dest)
        copied.append(dest)
        logger.info("Copied JSON → %s", dest)

    return copied


def save_pipeline_manifest(
    dest_dir: Path,
    *,
    records: list[PrecatorioRecord],
    refactor_stdout: str,
    refactor_stderr: str,
    refactor_exit_code: int,
    json_paths: list[Path],
) -> Path:
    manifest = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "precatorios": [
            {
                "numero_de_processo": r.numero_de_processo,
                "numero_do_incidente": r.numero_do_incidente,
                "processo_codigo": r.processo_codigo,
                "url": r.url,
                "txt_line": r.txt_line,
            }
            for r in records
        ],
        "refactor": {
            "exit_code": refactor_exit_code,
            "stdout_tail": refactor_stdout[-4000:],
            "stderr_tail": refactor_stderr[-4000:],
        },
        "json_outputs": [str(p) for p in json_paths],
    }
    path = dest_dir / f"manifest_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info("Pipeline manifest saved: %s", path)
    return path
